# Generated by Django 4.0.3 on 2022-03-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actor_description_en_actor_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='films',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='films',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='films',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='films',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='films',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='films',
            name='tagline_ru',
        ),
        migrations.RemoveField(
            model_name='films',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='films',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='fimshots',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='fimshots',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='fimshots',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='fimshots',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_ru',
        ),
    ]
